### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by zimbatm** [nix-community/vulnix#95]
Based on https://github.com/nix-community/vulnix/pull/80, the repo is no longer maintained. Let me know if I'm wrong @ckauhaus @ctheune.

**Comment by LeSuisse** [comment]
Last discourse thread on this topic: https://discourse.nixos.org/t/vulnix-new-maintainer-needed/27209

**Comment by henrirosten** [comment]
@zimbatm: I'd be happy to help maintain vulnix. Let me know if there are some concrete work items you need help with. Otherwise, I think getting rid of the ([to-be-retired](https://nvd.nist.gov/general/news/change-timeline)) NVD Legacy Data Feed [dependency](https://github.com/nix-community/vulnix/blob/ebd8ea84553c0fd95bc3042584b495560821500f/src/vulnix/nvd.py#L17) wold be something worth fixing as soon as possible to keep vulnix running.

**Comment by zimbatm** [comment]
Sounds like a great start! Any small cleanups, fixing the CI, basically non-controversial changes.

**Comment by ketzacoatl** [comment]
@zimbatm  / @henrirosten, what is the status of this project?

**Comment by zimbatm** [comment]
@henrirosten is now the new maintainer :tada:

**Comment by henrirosten** [comment]
Thanks @dschrempf, fixed with https://github.com/nix-community/vulnix/pull/104
